services:
  ecommerce-backend:
    build: .
    image: ecommerce_backend:1.0
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DATA_SOURCE: ${POSTGRES_DATA_SOURCE}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    container_name: ecommerce-backend
