version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: ecommerce
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
